FROM registry.poc-nci.codeocean.io/codeocean/r-studio:r-4.5.1-1.2204.0-rstudio-server-2025.05.1-513-ubuntu22.04

RUN Rscript -e 'install.packages(c("jsonlite", "dplyr", "tidyr", "ggplot2", "ggrepel", "stringr"), repos = "https://cloud.r-project.org")'
